server.port=8080

spring.jpa.database-platform=org.hibernate.community.dialect.Oracle12cDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

## UCP
spring.datasource.type=oracle.ucp.jdbc.PoolDataSource
spring.datasource.oracleucp.connection-factory-class-name=oracle.jdbc.pool.OracleDataSource
spring.datasource.oracleucp.sql-for-validate-connection=select * from dual
spring.datasource.oracleucp.connection-pool-name=connectionPoolName1
spring.datasource.oracleucp.initial-pool-size=15
spring.datasource.oracleucp.min-pool-size=10
spring.datasource.oracleucp.max-pool-size=30

spring.datasource.username=${db_user}
spring.datasource.password=${dbpassword}
spring.datasource.url=${db_url}
spring.datasource.driver-class-name=${driver_class_name}

logging.level.root=INFO

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

deepseek.api.key=${DEEPSEEK_API_KEY}
deepseek.api.url=https://api.deepseek.com/v1/chat/completions

telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.bot.name=${TELEGRAM_BOT_NAME}

openai.api.key=${OPENAI_API_KEY}

oracle.net.tns_admin=/mtdrworkshop/creds
